### ISSUE TITLE
Network errors downloading files

### ISSUE THREAD

**Issue by matham** [neurodata/ndreg-old#50]
So I have been trying to get started with this so that I can use it to register clarity brains. However, I ran into some issues working through the ipython notebooks.

I'm running it in docker and I tried the https://github.com/neurodata/ndreg/blob/master/doc/3D_CLARITY_RegistrationAndAnalysis.ipynb tutorial. However, when I try to download an image with 

```
>>> refToken = "ara_ccf2"
>>> refImg = imgDownload(refToken)
```

I get 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ndreg/ndreg.py", line 151, in imgDownload
    array = nd.get_cutout(token, channel, offset[0], size[0], offset[1], size[1], offset[2], size[2], resolution)
  File "/usr/local/lib/python2.7/dist-packages/ndio/remote/neurodata.py", line 97, in wrapped
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ndio/remote/neurodata.py", line 572, in get_cutout
    b[2][0], b[2][1], neariso=neariso)
  File "/usr/local/lib/python2.7/dist-packages/ndio/remote/neurodata.py", line 633, in _get_cutout_blosc_no_chunking
    req.text))
IOError: Bad server response for http://openconnecto.me/ocp/ca/ara_ccf2/average/blosc/0/0,456/0,320/16,32/: 404: (1049, "Unknown database 'ara_ccf2'")
```

I have seen the notice of some database error on the main site, but it's not clear exactly what it's affecting as I'm still able to browse some of the images.

**Comment by kkutten1** [comment]
Yeah @toekneesunshine had the same problem (See https://github.com/neurodata/ndreg/issues/49).   You need to update ndio and ndreg to the latest version.  Also you should probably try 
https://github.com/neurodata/ndreg/blob/master/doc/s275_Registration.ipynb as that notebook out of date.
